# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20170606_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slogan',
            field=models.TextField(default='Slogan'),
        ),
    ]
