# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_auto_20170606_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slogan',
            field=models.TextField(default='default_slogan'),
        ),
    ]
