# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_auto_20170606_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
