# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Main'), (2, 'About good'), (3, 'About us'), (4, 'Contacts')], default=0)),
                ('pattern_type', models.IntegerField(choices=[(1, 'Color'), (2, 'Image'), (3, 'Color and image'), (4, 'Seperate header')], default=1)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('image', models.CharField(default='', max_length=1000)),
                ('h_color', models.CharField(default='#000000', max_length=30)),
                ('h_size', models.IntegerField(default=25)),
                ('p_color', models.CharField(default='#000000', max_length=30)),
                ('p_size', models.IntegerField(default=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='features',
            name='about_good_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='about_good_h_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='about_good_image',
        ),
        migrations.RemoveField(
            model_name='features',
            name='about_good_p_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='about_good_type',
        ),
        migrations.RemoveField(
            model_name='features',
            name='about_us_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='about_us_h_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='about_us_image',
        ),
        migrations.RemoveField(
            model_name='features',
            name='about_us_p_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='about_us_type',
        ),
        migrations.RemoveField(
            model_name='features',
            name='contacts_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='contacts_h_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='contacts_image',
        ),
        migrations.RemoveField(
            model_name='features',
            name='contacts_p_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='contacts_type',
        ),
        migrations.RemoveField(
            model_name='features',
            name='h_size',
        ),
        migrations.RemoveField(
            model_name='features',
            name='main_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='main_h_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='main_h_size',
        ),
        migrations.RemoveField(
            model_name='features',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='features',
            name='main_p_color',
        ),
        migrations.RemoveField(
            model_name='features',
            name='main_p_size',
        ),
        migrations.RemoveField(
            model_name='features',
            name='main_type',
        ),
        migrations.RemoveField(
            model_name='features',
            name='p_size',
        ),
    ]
