# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slogan', models.TextField()),
                ('logo', models.ImageField(default=None, null=True, upload_to='images')),
                ('about_us', models.TextField()),
                ('about_good', models.TextField()),
                ('contacts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default="main\nattachment: scroll\npage-height: 100vh\nbackground: images/main.jpg\nlogo: images/l.png\nlogo-width: 189\nlogo-height: 136\nlogo-position: top left\nfont-size: 22px\nheader-size: 45px\nfont-family: 'Arial'\nfont-color: #dbdbdb\ninf-block-width: 75%\ninf-block-align: center\ninf-block-v-align: center\nmain-text-size: 90px\nmain-text-color: white\neffects: darken\nheader-color: white\ncolumns: none\n\nabout-us\nattachment: fixed\npage-height: 100vh\nbackground: white\neffects: none\nfont-family: 'Arial'\nheader-size: 30px\nheader-color: #121113\nmain-text-size: 90px\nmain-text-color: #121113\nfont-size: 14px\nfont-color: #8c8783\ninf-block-width: 60%\ninf-block-align: center\ninf-block-v-align: center\ncolumns: 1\nfl-bl-text-align: center\nfl-bl-header-align: center\nfl-image-position: top\nfl-block-background: none\nfl-single-image: none\nfl-image-form: square\n\nfeatures\nattachment: fixed\npage-height: 100vh\nbackground: white\neffects: none\nfont-family: 'Arial'\nheader-size: 30px\nheader-color: #121113\nmain-text-size: 90px\nmain-text-color: black\nfont-size: 14px\nfont-color: #8c8783\ninf-block-width: 60%\ninf-block-align: center\ninf-block-v-align: to-top\ncolumns: 2\nfl-bl-text-align: center\nfl-bl-header-align: center\nfl-image-position: top\nfl-block-background: none\nfl-single-image: none\nfl-image-form: square")),
            ],
        ),
        migrations.CreateModel(
            name='SiteParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.IntegerField(choices=[(1, 'Образовательные устлуги'), (2, 'Товары для детей'), (3, 'Разработка сайтов'), (4, 'Одежда'), (5, 'Товары для офиса')], default=1)),
                ('sex', models.IntegerField(choices=[(1, 'Мужчины'), (2, 'Женщины'), (3, 'Мужчины и женщины')], default=1)),
                ('age', models.IntegerField(choices=[(1, '5 - 15'), (2, '15-25'), (3, '25-55'), (4, '55+')], default=1)),
                ('target', models.IntegerField(choices=[(1, 'Клиенты'), (2, 'Бизнес')], default=1)),
                ('good_type', models.IntegerField(choices=[(1, 'Продажа товара'), (2, 'Оказание услуги')], default=1)),
            ],
        ),
    ]
