# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.IntegerField(choices=[(1, 'Образовательные устлуги'), (2, 'Товары для детей'), (3, 'Разработка сайтов'), (4, 'Одежда'), (5, 'Товары для офиса')], default=1)),
                ('sex', models.IntegerField(choices=[(1, 'Мужчины'), (2, 'Женщины'), (3, 'Мужчины и женщины')], default=1)),
                ('age', models.IntegerField(choices=[(1, '5 - 15'), (2, '15-25'), (3, '25-55'), (4, '55+')], default=1)),
                ('target', models.IntegerField(choices=[(1, 'Клиенты'), (2, 'Бизнес')], default=1)),
                ('good_type', models.IntegerField(choices=[(1, 'Продажа товара'), (2, 'Оказание услуги')], default=1)),
            ],
        ),
    ]
