# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('slogan', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('about_us', models.TextField(blank=True)),
                ('about_good', models.TextField(blank=True)),
                ('contacts', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(default='Arial', max_length=250)),
                ('header_size', models.IntegerField(default=25)),
                ('p_size', models.IntegerField(default=12)),
                ('main_background', models.CharField(default='#ffffff', max_length=1000)),
                ('main_header_color', models.CharField(default='black', max_length=30)),
                ('main_header_size', models.IntegerField(default=90)),
                ('main_p_color', models.CharField(default='black', max_length=30)),
                ('main_p_size', models.IntegerField(default=45)),
                ('about_us_background', models.CharField(default='#ffffff', max_length=1000)),
                ('about_us_header_color', models.CharField(default='black', max_length=30)),
                ('about_us_p_color', models.CharField(default='black', max_length=30)),
                ('about_good_background', models.CharField(default='#ffffff', max_length=1000)),
                ('about_good_header_color', models.CharField(default='black', max_length=30)),
                ('about_good_p_color', models.CharField(default='black', max_length=30)),
                ('contacts_background', models.CharField(default='#ffffff', max_length=1000)),
                ('contacts_header_color', models.CharField(default='black', max_length=30)),
                ('contacts_p_color', models.CharField(default='black', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SiteParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.IntegerField(choices=[(1, 'Образовательные услуги'), (2, 'Товары для детей'), (3, 'Разработка сайтов'), (4, 'Одежда'), (5, 'Товары для офиса')], default=1)),
                ('sex', models.IntegerField(choices=[(1, 'Мужчины'), (2, 'Женщины'), (3, 'Мужчины и женщины')], default=1)),
                ('age', models.IntegerField(choices=[(1, '5 - 15'), (2, '15-25'), (3, '25-55'), (4, '55+')], default=1)),
                ('target', models.IntegerField(choices=[(1, 'Клиенты'), (2, 'Бизнес')], default=1)),
                ('good_type', models.IntegerField(choices=[(1, 'Продажа товара'), (2, 'Оказание услуги')], default=1)),
            ],
        ),
    ]
