# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='text',
        ),
        migrations.AddField(
            model_name='features',
            name='about_good_background',
            field=models.CharField(default='#ffffff', max_length=200),
        ),
        migrations.AddField(
            model_name='features',
            name='about_good_header_color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AddField(
            model_name='features',
            name='about_good_p_color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AddField(
            model_name='features',
            name='about_us_background',
            field=models.CharField(default='#ffffff', max_length=200),
        ),
        migrations.AddField(
            model_name='features',
            name='about_us_header_color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AddField(
            model_name='features',
            name='about_us_p_color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AddField(
            model_name='features',
            name='contacts_background',
            field=models.CharField(default='#ffffff', max_length=200),
        ),
        migrations.AddField(
            model_name='features',
            name='contacts_header_color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AddField(
            model_name='features',
            name='contacts_p_color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AddField(
            model_name='features',
            name='font_family',
            field=models.CharField(default='Arial', max_length=250),
        ),
        migrations.AddField(
            model_name='features',
            name='header_size',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='features',
            name='main_background',
            field=models.CharField(default='#ffffff', max_length=200),
        ),
        migrations.AddField(
            model_name='features',
            name='main_header_color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AddField(
            model_name='features',
            name='main_header_size',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='features',
            name='main_p_color',
            field=models.CharField(default='black', max_length=30),
        ),
        migrations.AddField(
            model_name='features',
            name='main_p_size',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='features',
            name='p_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='content',
            name='about_good',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='about_us',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='contacts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slogan',
            field=models.TextField(blank=True),
        ),
    ]
