# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170606_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='about_good_header',
            field=models.CharField(default='default_about_good_h', max_length=150),
        ),
        migrations.AlterField(
            model_name='siteparameters',
            name='age',
            field=models.IntegerField(choices=[(3, '5-15'), (2, '15-25'), (1, '25-55')], default=1),
        ),
    ]
