# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170606_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='about_good_header',
            field=models.CharField(blank=True, default='Meet Django', max_length=150),
        ),
        migrations.AlterField(
            model_name='content',
            name='about_good_text',
            field=models.TextField(blank=True, default='Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design. Built by experienced developers, it takes care of much of the hassle of Web development, so you can focus on writing your app without needing to reinvent the wheel. It’s free and open source.'),
        ),
        migrations.AlterField(
            model_name='content',
            name='about_us_header',
            field=models.CharField(blank=True, default='About the Django Software Foundation', max_length=150),
        ),
        migrations.AlterField(
            model_name='content',
            name='about_us_text',
            field=models.TextField(blank=True, default='Development of Django is supported by an independent foundation established as a 501(c)(3) non-profit. Like most open-source foundations, the goal of the Django Software Foundation is to promote, support, and advance its open-source project: in our case, the Django Web framework.'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contacts_header',
            field=models.CharField(blank=True, default='Stay in the loop', max_length=150),
        ),
        migrations.AlterField(
            model_name='content',
            name='contacts_text',
            field=models.TextField(blank=True, default='Subscribe to one of our mailing lists to stay up to date with everything in the Django community.'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(default='Django', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='slogan',
            field=models.TextField(blank=True, default='Django makes it easier to build better Web apps more quickly and with less code.'),
        ),
        migrations.AlterField(
            model_name='features',
            name='font_family',
            field=models.CharField(default='Palatino, "Palatino Linotype", "Book Antiqua", "Hoefler Text", Georgia, "Lucida Bright", Cambria, Times, "Times New Roman", serif', max_length=250),
        ),
    ]
