# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170609_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagefeatures',
            name='name',
        ),
    ]
