# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_pagefeatures_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagefeatures',
            old_name='h_color',
            new_name='header_color',
        ),
        migrations.RenameField(
            model_name='pagefeatures',
            old_name='p_color',
            new_name='text_color',
        ),
        migrations.RemoveField(
            model_name='pagefeatures',
            name='h_size',
        ),
        migrations.RemoveField(
            model_name='pagefeatures',
            name='p_size',
        ),
        migrations.AddField(
            model_name='pagefeatures',
            name='header_size',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='pagefeatures',
            name='text_size',
            field=models.IntegerField(default=20),
        ),
    ]
